// Generated by gencpp from file topomapping/Probability.msg
// DO NOT EDIT!


#ifndef TOPOMAPPING_MESSAGE_PROBABILITY_H
#define TOPOMAPPING_MESSAGE_PROBABILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace topomapping
{
template <class ContainerAllocator>
struct Probability_
{
  typedef Probability_<ContainerAllocator> Type;

  Probability_()
    : header()
    , content()
    , stamp()  {
    }
  Probability_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , content(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _content_type;
  _content_type content;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::topomapping::Probability_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topomapping::Probability_<ContainerAllocator> const> ConstPtr;

}; // struct Probability_

typedef ::topomapping::Probability_<std::allocator<void> > Probability;

typedef boost::shared_ptr< ::topomapping::Probability > ProbabilityPtr;
typedef boost::shared_ptr< ::topomapping::Probability const> ProbabilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topomapping::Probability_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topomapping::Probability_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topomapping::Probability_<ContainerAllocator1> & lhs, const ::topomapping::Probability_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.content == rhs.content &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topomapping::Probability_<ContainerAllocator1> & lhs, const ::topomapping::Probability_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topomapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::topomapping::Probability_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topomapping::Probability_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topomapping::Probability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topomapping::Probability_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topomapping::Probability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topomapping::Probability_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topomapping::Probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e3947f61c5dab14250e75399de0c646";
  }

  static const char* value(const ::topomapping::Probability_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e3947f61c5dab14ULL;
  static const uint64_t static_value2 = 0x250e75399de0c646ULL;
};

template<class ContainerAllocator>
struct DataType< ::topomapping::Probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topomapping/Probability";
  }

  static const char* value(const ::topomapping::Probability_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topomapping::Probability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Standard metadata for higher-level flow data types\n"
"Header header\n"
"string content\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.secs: seconds (stamp_secs) since epoch\n"
"# * stamp.nsecs: nanoseconds since stamp_secs\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::topomapping::Probability_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topomapping::Probability_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.content);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Probability_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topomapping::Probability_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topomapping::Probability_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.content);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPOMAPPING_MESSAGE_PROBABILITY_H
